stages:
  - build  

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
  artifacts:
    paths:
      - 'ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp3.1\ConsoleApp2.exe'
